name: "yarn setup"
description: "Setup yarn"
runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
    - name: Install yarn
      run: |
          npm install -g yarn
          yarn set version stable
      shell: bash
    - name: Install dependencies
      run: |
          yarn
      shell: bash
