name: "bun setup"
description: "Setup bun"
runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
    - uses: oven-sh/setup-bun@v1
    - run: bun install
      shell: bash
