name: "npm setup"
description: "Setup npm"

runs:
  using: composite
  steps:
  - uses: actions/setup-node@v3
    with:
      node-version-file: 'package.json'
      cache: 'npm'
  - name: Install dependencies
    run: npm ci
    shell: bash