name: ci
on: push
jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup
              uses: ./.github/actions/npm

            - name: static check
              run: npm run ci:check
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup
              uses: ./.github/actions/npm

            - name: test
              run: npm run ci:test-group
